### ISSUE TITLE
Issue with Pods relationship fields?

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-pods#6]
Hey Scott,

Apparently relationship fields aren't indexing correctly, any chance you could take a look?

Relationship field: https://d.pr/free/i/zoHbIw
Another screenshot: https://d.pr/free/i/R1W26O

Note from customer:

> I finally figured out the problem. Apparently the Pods integration plugin was breaking it. Once I removed that plugin, I saw these options in the dropdown and selected this one, it worked. Apparently the plugin was selecting the _pods_recipe_meal_category which wasn't working.

_Internal note: ticket #10923_

**Comment by mgibbs189** [comment]
Hey @sc0ttkclark would you be able to take a look at this? If not, that's fine too

**Comment by sc0ttkclark** [comment]
Is this closed because it’s fixed?

**Comment by mgibbs189** [comment]
@sc0ttkclark I tested a handful of different scenarios and the fix *seemed* to work fine

**Comment by mgibbs189** [comment]
Referring to https://github.com/FacetWP/facetwp-pods/commit/aef0ab1eac8ac622f24f2b7bcbda559aa808a913#comments

**Comment by sc0ttkclark** [comment]
Word
