### ISSUE TITLE
Filter by related post taxonomy

### ISSUE THREAD

**Issue by brady77** [FacetWP/facetwp-pods#7]
I'm using a combination of the Pods plugin, FacetWP plugin and the new FacetWP - Pods Integration plugin. With Pods I defined two custom post types: 
1. Resources (saved articles, pdfs, etc.)
1. Quotations (quotes from the resources above)

I have a custom hierarchical taxonomy _Topics_ to classify the Resources (like Mathematics, IT etc). Between Resources and Quotations there is a bidirectional _relationship_ field. 

On the custom page I have a list of all Quotations that are faceted (filtered) by the related Resources. That works as expected. But I want to go one step deeper and filter the Quotations by Resource's Topics. How can I do it?

Thanks.

**Comment by sc0ttkclark** [comment]
This is not yet possible, it's a great idea though. I think it may be pretty cool to be able to filter posts by a traversal (resources.topic = "Some topic"). I don't have an ETA for that though, I'm focused on Pods core development for the time being and this add-on will be receiving only bug fixes until the next phase where I dig into features/enhancements like this. Depends on how many people ask for it honestly, I have to manage my time as effectively as possible these days :)

**Comment by brady77** [comment]
This plugin is a great relief for Pods/FacetWP/PHP newcomers (as I am) because it brings faceted filtering for _relationship fields_. Before this plugin was released I had to cope with custom hooks / functions to make relationship field available in FacetWP filters. The proposed enhancement follows the same logic - to make the PODs and FacetWP much more powerful and user-friendly together.

Could you give me some advice how to make this traversal-filtering via PHP code before you eventually make it part of the plugin? Thank you.
