### ISSUE TITLE
Template query visual mode editor problem

### ISSUE THREAD

**Issue by brady77** [FacetWP/facetwp-pods#8]
Visual mode query filtered by 'EXISTS' does not return correct values compared to the manually specified query (below the image):
![image](https://user-images.githubusercontent.com/8817469/45188229-ca2fb300-b233-11e8-889d-b2ef2a064249.png)

```
<?php
return array(
    'post_type' => 'resource',
    'post_status' => 'publish',
    'posts_per_page' => 15,
    'meta_key' => 'resource_quotation',
    'meta_compare' => 'EXIST',
);
```

**Comment by sc0ttkclark** [comment]
I don't know if this is a Pods FacetWP problem, this is just because Pods stores certain types of fields in the DB even if they are blank I believe. So you'd need to do:

```php
	'meta_query' => array(
		array(
			'key' => 'resource_quotation',
			'value' => ''
			'compare' = '!=',
		),
	),
```

Further, your original code example has `EXIST` instead of `EXISTS`, that might have been a problem to start with. Not sure if that's a FacetWP bug in itself (cc: @mgibbs189)

**Comment by brady77** [comment]
Well, that's my typo. Surprisingly, it doesn't make any difference in returned results: both the EXIST and EXISTS setting filters as expected (verified on data stored in database). The same aplies to your proposed query params with '!=' operator.

On the other side, the visual query builder does not return ANY records based on the settings from image. I should have stated it clearly in my first post. 

Before I installed the facetwp-pods plugin i was using the visual query editor as well. As far as I remember the dropdown list was populated a bit differently: there were 'just' raw custom field names (compared to the user-friendly names/labels after the plugin was activated). But the query logic worked on those real field names. That is why I decided to fill in the issue under this plugin and not the FacetWP. Unfortunately, I cannot verify this it on my active WP installation:  if I disable the plugin I will loose the 'data source' setting in configured facets. 

Should I provide some other info to help with debugging, please let me know.

**Comment by mgibbs189** [comment]
@brady77 if this is still an issue, please export the template so we can see it. `Settings > FacetWP > Settings` and export the template in question via the Backup area.
